name: backend_dart
description: CheapFood backend — proxies requests to menu_scraper microservice.
version: 0.0.1

environment:
  sdk: ^3.7.0

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  http: ^1.2.2
  crypto: ^3.0.6
  dart_jsonwebtoken: ^2.14.3
  common_dart:
    path: ../common_dart
  shelf_rate_limiter: ^1.0.1
  shelf_static: ^1.1.3
  path: ^1.9.0

dev_dependencies:
  lints: ^5.0.0
